name: Greet Contributor upon issue creation or pull request

on:
  pull_request:
    branches:
      - main
      - sub
  issues:
    types: [opened, labeled]

jobs:
  Print-On-pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Run Repository
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for opening an issue! We will look into it shortly."
          pr-message: "Thank you for your pull request! We will review it soon."
