name: Webhook Trigger Event

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Script
        run: |
          echo "Event Of Type: $GITHUB_EVENT_NAME"
